// ==UserScript==
// @name         GoGon Guide Relay
// @namespace    gogon
// @version      1.0.0
// @description  Reads the guide pages GoGon asks for (one at a time) and sends parsed records to your GoGon control plane over 127.0.0.1.
// @match        https://guide.fallensword.com/*
// @grant        GM_xmlhttpRequest
// @grant        GM_getValue
// @grant        GM_setValue
// @grant        GM_registerMenuCommand
// @connect      127.0.0.1
// @run-at       document-idle
// @noframes
// ==/UserScript==
// GENERATED by scripts/catalog/build-relay-userscript.mjs from catalog/contracts/guide.js, catalog/contracts/classify.js, catalog/guideParsers.js, catalog/relayClient.js. Do not edit.
// catalog-sync-v1 CAT-TASK-010. Setup: in the GoGon Catalog tab enable a guide_discovery job and
// issue a relay token; in Tampermonkey open this script's Storage tab and set "gogonRelayToken" to
// it (and "gogonRelayPort" if the control plane is not on 8787); open the SSH tunnel; open any
// guide.fallensword.com page and press Start.

(function () {
    'use strict';

    // --- inlined from catalog/contracts/guide.js ---
    // catalog/contracts/guide.js - CAT-TASK-001 / AC-CAT-011, AC-CAT-012, AC-CAT-015 (catalog-sync-v1 1.2.x)
    // The Fallen Sword guide as a catalog source, taken from the supplied userscripts in
    // reconciliation/scrappers (item, creature, and realm/master-realm scrapers). This module is also
    // inlined into the relay userscript (scripts/catalog/build-relay-userscript.mjs), so it has no
    // imports and only plain data and pure functions.
    //
    // Ordering: owner-attested 2026-09-28 (DEC-CAT-017). Index page 0 holds the newest records and the
    // last page the oldest. It is still checked on every run (descending IDs within and across pages);
    // a violation turns that kind back to full sweeps (AC-CAT-012).

    const GUIDE_ORIGIN = 'https://guide.fallensword.com';
    const GUIDE_KINDS = Object.freeze(['item', 'creature', 'realm', 'master_realm']);

    /** Code-owned URL shapes. Only a non-negative page index or a positive ID is ever substituted. */
    const GUIDE_URLS = Object.freeze({
        item: Object.freeze({
            index: '/index.php?cmd=items&index={page}',
            detail: '/index.php?cmd=items&subcmd=view&item_id={id}',
            idParam: 'item_id',
        }),
        creature: Object.freeze({
            index: '/index.php?cmd=creatures&index={page}&search_name=&search_level_min=-1&search_level_max=-1&search_class=-1&search_type=-1',
            detail: '/index.php?cmd=creatures&subcmd=view&creature_id={id}',
            idParam: 'creature_id',
        }),
        realm: Object.freeze({
            index: '/index.php?cmd=realms&index={page}',
            detail: '/index.php?cmd=realms&subcmd=view&realm_id={id}',
            idParam: 'realm_id',
        }),
        master_realm: Object.freeze({
            index: '/index.php?cmd=masterrealms&index={page}',
            detail: '/index.php?cmd=masterrealms&subcmd=view&masterrealm_id={id}',
            idParam: 'masterrealm_id',
        }),
    });

    const GUIDE_ORDERING = Object.freeze({
        order: 'newest_first',
        firstIndex: 0,
        attestedBy: 'owner',
        attestedOn: '2026-09-28',
        runtimeCheck: 'descending_ids',
    });

    const MAX_GUIDE_ID = 10_000_000;
    const MAX_GUIDE_PAGE = 10_000;

    /** Builds a guide URL from a code-owned template; anything but a bounded integer is refused. */
    function guideUrl(kind, phase, value) {
        const spec = GUIDE_URLS[kind];
        if (!spec || (phase !== 'index' && phase !== 'detail')) throw new Error('Unknown guide request.');
        const ok = phase === 'index'
            ? Number.isSafeInteger(value) && value >= 0 && value <= MAX_GUIDE_PAGE
            : Number.isSafeInteger(value) && value > 0 && value <= MAX_GUIDE_ID;
        if (!ok) throw new Error('Guide page or ID out of range.');
        return GUIDE_ORIGIN + spec[phase].replace(phase === 'index' ? '{page}' : '{id}', String(value));
    }

    /**
     * The newest-first check for one page of IDs in document order (duplicates already removed).
     * @param {number[]} ids - this page
     * @param {number|null} previousMin - the smallest ID of the previous page, or null for page 0
     * @returns {boolean} true when the page is strictly descending and entirely below previousMin
     */
    function isDescendingPage(ids, previousMin) {
        for (let i = 1; i < ids.length; i++) if (!(ids[i] < ids[i - 1])) return false;
        return previousMin === null || ids.length === 0 || ids[0] < previousMin;
    }

    // --- inlined from catalog/contracts/classify.js ---
    // catalog/contracts/classify.js - CAT-TASK-001 / AC-CAT-003, AC-CAT-004, AC-CAT-011 (catalog-sync-v1 1.2.x)
    // Classifies a game or guide response before anything reads it. Only 'ok' may be parsed; every other
    // class leaves the cursor where it is (catalog-sync constraint). Inlined into the relay userscript,
    // so it has no imports.
    //
    // Classes: ok | challenge | login | unauthenticated | rate_limited | server_error | not_found |
    //          http_error | malformed | too_large
    // A Cloudflare challenge is only recognized and reported; nothing here tries to complete one.

    const MAX_RESPONSE_BYTES = 2 * 1024 * 1024;

    // Markers of a Cloudflare interstitial or managed challenge (title, script, and form signatures).
    const CHALLENGE_MARKERS = [
        /<title>\s*Just a moment\.\.\.\s*<\/title>/i,
        /\/cdn-cgi\/challenge-platform\//i,
        /\bcf[_-]chl[_-]/i,
        /\bchallenge-form\b/i,
        /Attention Required! \| Cloudflare/i,
    ];
    // The game's login page (the same signature utils.js secureFetch uses).
    const LOGIN_MARKER = /\bid\s*=\s*["']hc-account-link["']/i;

    /**
     * @param {object} res
     * @param {number} res.status
     * @param {string} [res.contentType]
     * @param {string|null} [res.cfMitigated] - the cf-mitigated response header
     * @param {string} res.body - response text (already read)
     * @param {'json'|'html'} expect
     * @returns {{ class: string, reason: string, json?: any }}
     */
    function classifyResponse({ status, contentType = '', cfMitigated = null, body = '' }, expect) {
        const text = typeof body === 'string' ? body : '';
        if (text.length > MAX_RESPONSE_BYTES) return { class: 'too_large', reason: 'response exceeds the byte limit' };
        const isHtml = /text\/html/i.test(contentType) || /^\s*</.test(text);
        if (String(cfMitigated || '').toLowerCase() === 'challenge' || (isHtml && CHALLENGE_MARKERS.some(m => m.test(text)))) {
            return { class: 'challenge', reason: 'cloudflare challenge' };
        }
        if (status === 429) return { class: 'rate_limited', reason: 'HTTP 429' };
        if (status >= 500) return { class: 'server_error', reason: `HTTP ${status}` };
        if (status === 404) return { class: 'not_found', reason: 'HTTP 404' };
        if (status < 200 || status >= 300) return { class: 'http_error', reason: `HTTP ${status}` };
        if (isHtml && LOGIN_MARKER.test(text)) return { class: 'login', reason: 'login page' };

        if (expect === 'json') {
            let json;
            try { json = JSON.parse(text); } catch { return { class: 'malformed', reason: 'invalid JSON' }; }
            if (!json || typeof json !== 'object' || Array.isArray(json)) return { class: 'malformed', reason: 'JSON is not an object' };
            if (json.s === false) {
                return json.e && typeof json.e === 'object'
                    ? { class: 'unauthenticated', reason: 'game rejected the session' }
                    : { class: 'malformed', reason: 'unsuccessful game response' };
            }
            return { class: 'ok', reason: 'ok', json };
        }
        if (!isHtml) return { class: 'malformed', reason: 'not an HTML page' };
        return { class: 'ok', reason: 'ok' };
    }

    /** Classes after which the same request may be retried later without being counted as data. */
    const RETRYABLE = Object.freeze(['rate_limited', 'server_error', 'http_error']);

    // --- inlined from catalog/guideParsers.js ---
    // catalog/guideParsers.js - CAT-TASK-001 / AC-CAT-011, AC-CAT-013 (catalog-sync-v1 1.2.x)
    // Guide page parsers, ported from the supplied userscripts in reconciliation/scrappers
    // (fallen_sword_item_scraper.js parseItemPage, fallen_sword_creature_scraper.js parseCreatureFromDoc,
    // fallen_sword_realm_scraper.js parseRealmPage / parseMasterRealmPage). They run in the owner's
    // browser inside the relay userscript (inlined by scripts/catalog/build-relay-userscript.mjs) and in
    // Node tests on linkedom, so they use only querySelectorAll/getAttribute/textContent and have no
    // imports. Output is plain data in the relay wire shape; the server validates it again
    // (catalog/guideNormalizers.js) and never trusts it. A page without a name is not a record.

    const PARSER_BASE = 'https://guide.fallensword.com/';
    const PARSER_LIMITS = { name: 191, text: 8192, list: 500 };

    function cleanText(value, max = PARSER_LIMITS.name) {
        const t = String(value ?? '').replace(/ |&nbsp;/g, ' ').replace(/\s+/g, ' ').trim();
        return t ? t.slice(0, max) : null;
    }

    function toInt(value) {
        const n = parseInt(String(value ?? '').replace(/,/g, ''), 10);
        return Number.isSafeInteger(n) ? n : null;
    }

    function idFromHref(href, param) {
        const m = String(href ?? '').match(new RegExp(`[?&]${param}=(\\d{1,9})(?:&|$|#)`));
        const n = m ? Number(m[1]) : null;
        return n && n > 0 ? n : null;
    }

    /** An https image URL on a fallensword.com host, or null. */
    function imageUrl(src) {
        if (!src) return null;
        try {
            const u = new URL(String(src), PARSER_BASE);
            u.protocol = 'https:';
            if (!/(^|\.)fallensword\.com$/i.test(u.hostname) || u.username || u.password) return null;
            const s = u.toString();
            return s.length <= 512 ? s : null;
        } catch { return null; }
    }

    /** A page from the guide itself: it carries the guide's own index.php?cmd= navigation. */
    function isGuidePage(doc) {
        return Boolean(doc?.querySelector?.('a[href*="index.php?cmd="]'));
    }

    /**
     * Index page: IDs in document order (first occurrence), each with its link text as a name hint.
     * @returns {{ entries: Array<{ id: number, name: string|null }> }}
     */
    function parseIndexPage(doc, idParam) {
        const seen = new Map();
        for (const a of doc.querySelectorAll(`a[href*="${idParam}="]`)) {
            const id = idFromHref(a.getAttribute('href'), idParam);
            if (!id) continue;
            const name = cleanText(a.textContent);
            if (!seen.has(id)) seen.set(id, name);
            else if (!seen.get(id) && name) seen.set(id, name);
            if (seen.size >= PARSER_LIMITS.list) break;
        }
        return { entries: [...seen].map(([id, name]) => ({ id, name })) };
    }

    function headerNameAndLevel(doc) {
        const header = cleanText(doc.querySelector('.tHeader b')?.textContent, 300);
        if (!header) return { name: null, minLevel: null };
        const m = header.match(/^(.+?)\s*\(Min\s*Level:\s*(\d+)\)$/i);
        return m ? { name: cleanText(m[1]), minLevel: Number(m[2]) } : { name: cleanText(header), minLevel: null };
    }

    // --- item ------------------------------------------------------------------------------------------

    const RARITIES = ['common', 'uncommon', 'rare', 'unique', 'legendary', 'epic', 'super elite', 'crystalline'];
    const STAT_LABELS = {
        Type: 'type', Level: 'level', Attack: 'attack', Defense: 'defense', Armor: 'armor', Damage: 'damage', HP: 'hp',
        'XP Gain': 'xpGain', Stamina: 'stamina', 'Stamina Gain': 'staminaGain', 'Gold Gain': 'goldGain',
    };

    function readStats(cells, into) {
        for (let i = 0; i + 1 < cells.length; i += 2) {
            const label = cleanText(cells[i].textContent)?.replace(/:$/, '');
            const key = STAT_LABELS[label];
            if (!key) continue;
            const raw = cleanText(cells[i + 1].textContent, 64);
            into[key] = key === 'type' ? raw : toInt(raw);
        }
    }

    function readEnhancements(cells, into) {
        for (let i = 0; i + 1 < cells.length; i += 2) {
            const name = cleanText(cells[i].textContent)?.replace(/:$/, '');
            const m = String(cells[i + 1].textContent).match(/(\d+)%/);
            if (name && m && into.length < 64) into.push({ name, value: Number(m[1]) });
        }
    }

    function parseItemDetail(doc, id) {
        let name = null;
        let rarity = null;
        for (const cell of doc.querySelectorAll('td.tHeader[colspan="10"]')) {
            const bold = cleanText(cell.querySelector('b')?.textContent);
            if (!bold) continue;
            const rest = cleanText(cell.textContent, 300)?.replace(bold, '').trim() ?? '';
            if (rest.startsWith('(') && rest.endsWith(')')) {
                const inner = rest.slice(1, -1).trim();
                if (RARITIES.some(r => inner.toLowerCase().startsWith(r))) { name = bold; rarity = cleanText(inner, 64); break; }
            } else if (bold.length > 3) { name = bold; break; }
        }
        if (!name) return null;

        const stats = {};
        const enhancements = [];
        const droppedBy = [];
        const setStats = {};
        const setEnhancements = [];
        let setName = null;
        let setId = null;
        let section = null;
        for (const row of doc.querySelectorAll('tr')) {
            const cells = [...row.querySelectorAll('td')];
            if (!cells.length) continue;
            if (cells.length === 1 && cells[0].classList.contains('tHeader') && cells[0].querySelector('b')) {
                section = cleanText(cells[0].querySelector('b').textContent);
                continue;
            }
            if (section === 'Statistics') readStats(cells, stats);
            else if (section === 'Enhancements') readEnhancements(cells, enhancements);
            else if (section === 'Dropped By' && cells.length >= 2) {
                const creatureName = cleanText(cells[0].textContent)?.replace(/:$/, '');
                const m = String(cells[1].textContent).match(/([\d.]+)%/);
                if (creatureName && m && droppedBy.length < 200) droppedBy.push({ creatureName, dropRate: Number(m[1]) });
            } else if (section === 'Set Bonuses') {
                const link = cells.length === 1 ? cells[0].querySelector('a[href*="search_set_id"]') : null;
                if (link) {
                    setName = cleanText(link.textContent);
                    setId = idFromHref(link.getAttribute('href'), 'search_set_id');
                } else if (cells.length > 1) {
                    readStats(cells.filter(c => cleanText(c.textContent)), setStats);
                }
            } else if (section === 'Set Enhancements') readEnhancements(cells, setEnhancements);
        }
        const image = doc.querySelector('img[src*="cdn"]');
        const isSet = Boolean(setName || setEnhancements.length);
        return {
            id,
            name,
            rarity,
            imageUrl: imageUrl(image?.getAttribute('src')),
            stats,
            enhancements,
            droppedBy,
            setId,
            setName,
            setBonuses: isSet ? { ...setStats, enhancements: setEnhancements } : null,
        };
    }

    // --- creature --------------------------------------------------------------------------------------

    const RANGE_STATS = { 'Attack:': 'attack', 'Defense:': 'defense', 'Armor:': 'armor', 'Damage:': 'damage', 'HP:': 'hp', 'Gold:': 'gold', 'XP:': 'xp' };

    function parseCreatureDetail(doc, id) {
        const name = cleanText(doc.querySelector('.tHeader b')?.textContent);
        if (!name) return null;
        const rows = [...doc.querySelectorAll('tr')];
        let description = null;
        for (let i = 0; i < rows.length; i++) {
            if (cleanText(rows[i].querySelector('.tHeader b')?.textContent) !== name) continue;
            const cell = rows[i + 1]?.querySelector('td[colspan="10"]');
            if (cell && !cell.classList.contains('tHeader')) description = cleanText(cell.textContent, PARSER_LIMITS.text);
            break;
        }
        const stats = {};
        const cells = [...doc.querySelectorAll('td')];
        cells.forEach((cell, i) => {
            const label = cleanText(cell.textContent, 32);
            if (label === 'Class:') stats.class = cleanText(cells[i + 1]?.textContent, 64);
            else if (label === 'Level:') { const v = toInt(cells[i + 1]?.textContent); if (v !== null) stats.level = v; }
            else if (RANGE_STATS[label]) {
                const min = toInt(cells[i + 1]?.textContent);
                const max = toInt(cells[i + 3]?.textContent);
                if (min !== null && max !== null) stats[RANGE_STATS[label]] = { min, max };
            }
        });
        const enhancements = [];
        let inEnhancements = false;
        for (const row of rows) {
            const header = row.querySelector('.tHeader');
            if (header && /Enhancements/.test(header.textContent)) { inEnhancements = true; continue; }
            if (inEnhancements && header) inEnhancements = false;
            if (inEnhancements) {
                const text = cleanText(row.textContent, 256);
                if (text && !text.includes('[no enhancements]') && enhancements.length < 64) enhancements.push(text);
            }
        }
        const droppedItems = [];
        const seenItems = new Set();
        for (const a of doc.querySelectorAll('a[href*="item_id="]')) {
            const itemId = idFromHref(a.getAttribute('href'), 'item_id');
            if (!itemId || seenItems.has(itemId) || droppedItems.length >= 200) continue;
            seenItems.add(itemId);
            droppedItems.push({ itemId, itemName: cleanText(a.textContent) });
        }
        const realms = [];
        const seenRealms = new Set();
        for (const a of doc.querySelectorAll('a[href*="realm_id="]')) {
            const realmId = idFromHref(a.getAttribute('href'), 'realm_id');
            if (!realmId || seenRealms.has(realmId) || realms.length >= 200) continue;
            seenRealms.add(realmId);
            realms.push({ realmId, realmName: cleanText(a.textContent) });
        }
        return {
            id, name, description, stats, enhancements, droppedItems, realms,
            imageUrl: imageUrl(doc.querySelector('.creatureImg img')?.getAttribute('src')),
        };
    }

    // --- realm and master realm --------------------------------------------------------------------------

    function linkList(doc, param, max = 200) {
        const out = [];
        const seen = new Set();
        for (const a of doc.querySelectorAll(`a[href*="${param}="]`)) {
            const id = idFromHref(a.getAttribute('href'), param);
            if (!id || seen.has(id) || out.length >= max) continue;
            seen.add(id);
            out.push({ id, name: cleanText(a.textContent), anchor: a });
        }
        return out;
    }

    function parseRealmDetail(doc, id) {
        const { name, minLevel } = headerNameAndLevel(doc);
        if (!name) return null;
        const stairways = [];
        const seenStairs = new Set();
        for (const img of doc.querySelectorAll('a[href*="realm_id="] img[src*="stairways"]')) {
            const target = idFromHref(img.closest('a')?.getAttribute('href'), 'realm_id');
            if (!target || seenStairs.has(target)) continue;
            seenStairs.add(target);
            const tip = String(img.getAttribute('onmouseover') ?? '').match(/Stairway to (.+?)['"]?\)/);
            stairways.push({ targetRealmId: target, targetRealmName: cleanText(tip?.[1]) });
        }
        return {
            id, name, minLevel,
            shops: linkList(doc, 'shop_id').map(s => ({ shopId: s.id, shopName: s.name })),
            relics: linkList(doc, 'relic_id').map(r => r.name).filter(Boolean),
            quests: linkList(doc, 'quest_id').map(q => ({ questId: q.id, questName: q.name })).filter(q => q.questName),
            creatures: linkList(doc, 'creature_id').map(c => ({ creatureId: c.id, creatureName: c.name })),
            stairways,
        };
    }

    function parseMasterRealmDetail(doc, id) {
        const { name, minLevel } = headerNameAndLevel(doc);
        if (!name) return null;
        return {
            id, name, minLevel,
            imageUrl: imageUrl(doc.querySelector('img[src*="masterrealms/"]')?.getAttribute('src')),
            realms: linkList(doc, 'realm_id').map(r => {
                const cells = r.anchor.closest('tr')?.querySelectorAll('td') ?? [];
                const level = cells.length > 1 ? String(cells[1].textContent).match(/(\d+)/) : null;
                return { realmId: r.id, realmName: r.name, minLevel: level ? Number(level[1]) : null };
            }),
        };
    }

    const DETAIL_PARSERS = { item: parseItemDetail, creature: parseCreatureDetail, realm: parseRealmDetail, master_realm: parseMasterRealmDetail };

    // --- inlined from catalog/relayClient.js ---
    // catalog/relayClient.js - CAT-TASK-010 / AC-CAT-011, AC-CAT-014 (catalog-sync-v1 1.3.0)
    // The browser half of the guide relay, inlined into the userscript by
    // scripts/catalog/build-relay-userscript.mjs together with the three modules imported below (the
    // build drops these import lines; the inlined modules put the same names in scope). runLease() reads exactly the pages or IDs the server's lease names, one at a time with the
    // lease's delay, classifies each response, parses it, and returns results in lease order. It stops at
    // the first challenge or unusable page, so the server keeps its cursor there. It never retries past a
    // challenge, never submits a challenge form, and never sees or sends cookies itself.

    /**
     * An incremental lease carries stopAtId (the kind's last_seen_id) and overlapPages: once a page
     * reaches stopAtId the relay reads overlapPages more and stops, as long as the pages it saw were in
     * descending order. The server applies the same rule and stays authoritative; this only saves requests.
     * @param {{ kind: string, work: Array<{ type: 'index'|'detail', page?: number, id?: number }>, minDelayMs: number, stopAtId?: number|null, overlapPages?: number }} lease
     * @param {object} deps
     * @param {(url: string) => Promise<{ status: number, contentType: string, cfMitigated: string|null, body: string }>} deps.fetchPage
     * @param {(html: string) => Document} deps.parseHtml
     * @param {(ms: number) => Promise<void>} deps.sleep
     * @param {() => boolean} [deps.stopped] - the owner pressed stop
     * @returns {Promise<Array<object>>} results in lease order (possibly fewer than the work items)
     */
    async function runLease(lease, { fetchPage, parseHtml, sleep, stopped = () => false }) {
        const results = [];
        const spec = GUIDE_URLS[lease.kind];
        let reachedAt = null;       // incremental: the page that reached stopAtId
        let descending = true;
        let prevMin = null;
        for (let i = 0; i < lease.work.length; i++) {
            if (stopped()) break;
            if (i > 0) await sleep(lease.minDelayMs);
            const item = lease.work[i];
            const key = item.type === 'index' ? { type: 'index', page: item.page } : { type: 'detail', id: item.id };
            let res;
            try {
                res = await fetchPage(guideUrl(lease.kind, item.type, item.type === 'index' ? item.page : item.id));
            } catch {
                results.push({ ...key, outcome: 'error' });
                break;
            }
            const cls = classifyResponse({ status: res.status, contentType: res.contentType, cfMitigated: res.cfMitigated, body: res.body }, 'html');
            if (cls.class === 'challenge') { results.push({ ...key, outcome: 'challenge' }); break; }
            if (cls.class === 'not_found' && item.type === 'detail') { results.push({ ...key, outcome: 'missing' }); continue; }
            if (cls.class !== 'ok') { results.push({ ...key, outcome: 'error' }); break; }
            const doc = parseHtml(res.body);
            if (!isGuidePage(doc)) { results.push({ ...key, outcome: 'invalid' }); break; }
            if (item.type === 'index') {
                const { entries } = parseIndexPage(doc, spec.idParam);
                if (!entries.length) { results.push({ ...key, outcome: 'empty' }); break; }   // past the last page
                results.push({ ...key, outcome: 'ok', entries });
                const ids = entries.map(e => e.id);
                descending = descending && isDescendingPage(ids, prevMin);
                prevMin = Math.min(...ids);
                if (descending && typeof lease.stopAtId === 'number' && reachedAt === null && prevMin <= lease.stopAtId) reachedAt = item.page;
                if (descending && reachedAt !== null && item.page >= reachedAt + (lease.overlapPages ?? 1)) break;
            } else {
                const record = DETAIL_PARSERS[lease.kind](doc, item.id);
                results.push(record ? { ...key, outcome: 'ok', record } : { ...key, outcome: 'missing' });
            }
        }
        return results;
    }

    // --- relay glue (userscript only) -------------------------------------------------------------
    const PORT_KEY = 'gogonRelayPort';
    const TOKEN_KEY = 'gogonRelayToken';
    const RUN_KEY = 'gogonRelayRunning';
    const LOCK_KEY = 'gogonRelayLock';
    const IDLE_POLL_MS = 5 * 60 * 1000;
    const ERROR_POLL_MS = 60 * 1000;
    const LOCK_STALE_MS = 90 * 1000;
    const STATUS_TEXT = {
        disabled: 'the guide job is not enabled in the Catalog tab.',
        paused: 'the guide job is paused.',
        idle: 'nothing is due; checking again later.',
        cap_reached: "today's guide request cap is used up.",
        busy: 'another browser is running the relay.',
    };
    const tabId = Math.random().toString(36).slice(2);
    let stopped = true;
    let heartbeat = null;

    const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));
    const port = () => {
        const p = Number(GM_getValue(PORT_KEY, 8787));
        return Number.isInteger(p) && p > 0 && p < 65536 ? p : 8787;
    };

    const panel = document.createElement('div');
    panel.style.cssText = 'position:fixed;bottom:8px;right:8px;z-index:2147483647;max-width:340px;padding:8px 10px;font:12px/1.4 system-ui,sans-serif;background:#1c2029;color:#e7eaf0;border:1px solid #2d3340;border-radius:8px';
    const statusLine = document.createElement('div');
    const toggle = document.createElement('button');
    toggle.type = 'button';
    toggle.style.cssText = 'margin-top:6px';
    panel.append(statusLine, toggle);
    document.body.append(panel);
    const show = text => { statusLine.textContent = 'GoGon relay: ' + text; };
    const refreshButton = () => { toggle.textContent = stopped ? 'Start' : 'Stop'; };

    function relayRequest(method, route, body, token) {
        return new Promise((resolve, reject) => {
            GM_xmlhttpRequest({
                method,
                url: 'http://127.0.0.1:' + port() + route,
                headers: { Authorization: 'Bearer ' + token, 'Content-Type': 'application/json' },
                data: body ? JSON.stringify(body) : undefined,
                timeout: 30000,
                anonymous: true,
                onload: r => { let json = null; try { json = JSON.parse(r.responseText); } catch { /* not JSON */ } resolve({ status: r.status, json }); },
                onerror: () => reject(new Error('unreachable')),
                ontimeout: () => reject(new Error('timeout')),
            });
        });
    }

    // Guide pages are read same-origin by this browser, with its own validated session.
    async function fetchPage(url) {
        const res = await fetch(url, { credentials: 'same-origin', redirect: 'follow' });
        return { status: res.status, contentType: res.headers.get('content-type') || '', cfMitigated: res.headers.get('cf-mitigated'), body: await res.text() };
    }
    const parseHtml = html => new DOMParser().parseFromString(html, 'text/html');

    async function cycle() {
        const token = GM_getValue(TOKEN_KEY, '');
        if (!token) { show('no relay token. In Tampermonkey, open this script\'s Storage tab and set gogonRelayToken.'); return stop(); }
        let r;
        try { r = await relayRequest('GET', '/relay/guide/lease', null, token); } catch { show('GoGon is not reachable on 127.0.0.1:' + port() + ' (is the SSH tunnel open?).'); return sleep(ERROR_POLL_MS); }
        if (r.status === 401) { show('the relay token is missing, expired, or revoked.'); return stop(); }
        if (r.status !== 200 || !r.json) { show('GoGon answered HTTP ' + r.status + '.'); return sleep(ERROR_POLL_MS); }
        if (r.json.status !== 'lease') { show(STATUS_TEXT[r.json.status] || String(r.json.status)); return sleep(IDLE_POLL_MS); }
        const lease = r.json.lease;
        show('reading ' + lease.work.length + ' ' + lease.kind + (lease.work[0].type === 'index' ? ' index' : ' detail') + ' page(s)...');
        const results = await runLease(lease, { fetchPage, parseHtml, sleep, stopped: () => stopped });
        let s;
        try { s = await relayRequest('POST', '/relay/guide/leases/' + lease.leaseId, { results }, token); } catch { show('could not send the results; trying again later.'); return sleep(ERROR_POLL_MS); }
        if (s.status !== 200) { show('GoGon refused the results (HTTP ' + s.status + ').'); return sleep(ERROR_POLL_MS); }
        const last = results[results.length - 1];
        if (last && last.outcome === 'challenge') { show('Cloudflare asked for a check. Complete it yourself on a guide page, then press Start.'); return stop(); }
        show('sent ' + results.length + ' result(s)' + (s.json && s.json.sweepComplete ? '; sweep complete' : '') + '.');
        return sleep(lease.minDelayMs);
    }

    function otherTabRunning() {
        const lock = GM_getValue(LOCK_KEY, null);
        return Boolean(lock && lock.tab !== tabId && Date.now() - lock.at < LOCK_STALE_MS);
    }

    function start() {
        if (!stopped) return;
        if (otherTabRunning()) { show('already running in another tab.'); return; }
        stopped = false;
        GM_setValue(RUN_KEY, true);
        GM_setValue(LOCK_KEY, { tab: tabId, at: Date.now() });
        heartbeat = setInterval(() => GM_setValue(LOCK_KEY, { tab: tabId, at: Date.now() }), 30 * 1000);
        refreshButton();
        (async () => {
            while (!stopped) {
                try { await cycle(); } catch { show('unexpected error; retrying in a minute.'); await sleep(ERROR_POLL_MS); }
            }
        })();
    }

    function stop() {
        stopped = true;
        GM_setValue(RUN_KEY, false);
        clearInterval(heartbeat);
        const lock = GM_getValue(LOCK_KEY, null);
        if (lock && lock.tab === tabId) GM_setValue(LOCK_KEY, null);
        refreshButton();
    }

    toggle.addEventListener('click', () => (stopped ? start() : stop()));
    GM_registerMenuCommand('GoGon relay: start', start);
    GM_registerMenuCommand('GoGon relay: stop', stop);
    refreshButton();
    show(GM_getValue(TOKEN_KEY, '') ? 'stopped.' : 'set gogonRelayToken in this script\'s Storage tab.');
    if (GM_getValue(RUN_KEY, false)) start();
})();
